//! Property-based tests for tokmd-python error invariants.
//!
//! This module verifies three critical invariants using proptest:
//! 1. Round-trip: Python error → Rust error → Python error (identity preserved)
//! 2. Monotonicity: More invalid inputs → More errors (never fewer)
//! 3. No panic: Any input → PyResult (never panic)

use proptest::prelude::*;
use serde_json::Value;

// Import the core FFI directly for testing error invariants
use tokmd_core::ffi::run_json;

/// Strategy for generating valid mode strings
fn mode_strategy() -> impl Strategy<Value = String> {
    proptest::string::string_regex("[a-zA-Z0-9_-]{0,50}").unwrap()
}

/// Strategy for generating args strings (valid JSON fragments)
fn args_strategy() -> impl Strategy<Value = String> {
    proptest::string::string_regex("\\{.*\\}|\\[.*\\]|null|true|false|[0-9]+|\"[^\"]*\"|").unwrap()
}

/// Strategy for generating field names that accept boolean values
fn boolean_field_strategy() -> impl Strategy<Value = String> {
    prop_oneof!(
        Just("hidden".to_string()),
        Just("files".to_string()),
        Just("no_ignore".to_string()),
        Just("no_ignore_parent".to_string()),
        Just("no_ignore_dot".to_string()),
        Just("no_ignore_vcs".to_string()),
        Just("hidden".to_string()),
    )
}

/// Strategy for generating mode/field pairs for numeric settings that are
/// actually validated by that mode's JSON interface.
fn numeric_field_strategy() -> impl Strategy<Value = (String, String)> {
    prop_oneof!(
        Just(("lang".to_string(), "top".to_string())),
        Just(("module".to_string(), "top".to_string())),
        Just(("module".to_string(), "module_depth".to_string())),
        Just(("export".to_string(), "min_code".to_string())),
        Just(("export".to_string(), "max_rows".to_string())),
    )
}

/// Strategy for generating invalid string values that aren't valid for the field type
fn invalid_value_strategy() -> impl Strategy<Value = String> {
    prop_oneof!(
        Just("not_a_bool".to_string()),
        Just("invalid".to_string()),
        Just("string".to_string()),
        Just("abc".to_string()),
    )
}

/// Strategy for generating unknown mode strings
fn unknown_mode_strategy() -> impl Strategy<Value = String> {
    prop_oneof!(
        Just("unknown".to_string()),
        Just("invalid".to_string()),
        Just("foo".to_string()),
        Just("bar".to_string()),
        Just("baz".to_string()),
        Just("test_mode".to_string()),
        Just("mode_xyz".to_string()),
    )
}

// Property 1: Error Round-Trip
//
// Invariant: Any error generated by the core FFI must be representable
// as a valid JSON envelope and contain non-empty error context.
//
// This verifies that:
// - Rust TokmdError → JSON envelope → preserves message
// - Envelope extraction → Python TokmdError → preserves message
proptest! {
    /// Test that any mode string with any args returns valid JSON envelope.
    #[test]
    fn prop_run_json_always_returns_valid_json(
        mode in mode_strategy(),
        args in args_strategy()
    ) {
        let result = run_json(&mode, &args);

        // Invariant: Must be valid JSON
        let envelope: Value = serde_json::from_str(&result)
            .expect("run_json must always return valid JSON");

        // Invariant: Must have 'ok' field
        prop_assert!(
            envelope.get("ok").is_some(),
            "Envelope must contain 'ok' field"
        );

        // Invariant: If ok=false, must have error field with message
        if envelope["ok"] == false {
            prop_assert!(
                envelope.get("error").is_some(),
                "Error envelope must contain 'error' field"
            );

            let error = &envelope["error"];
            prop_assert!(
                error.get("code").is_some(),
                "Error must contain 'code' field"
            );
            prop_assert!(
                error.get("message").is_some(),
                "Error must contain 'message' field"
            );

            // Verify error message is non-empty
            let msg = error["message"].as_str().unwrap_or("");
            prop_assert!(
                !msg.is_empty(),
                "Error message must not be empty"
            );
        }
    }

    /// Test that invalid JSON in args returns proper error envelope.
    #[test]
    fn prop_invalid_json_returns_error_envelope(
        invalid_json in proptest::string::string_regex("[^\\{\\[][^:]*|\\{[^}]*|\\[.*").unwrap()
    ) {
        let result = run_json("lang", &invalid_json);
        let envelope: Value = serde_json::from_str(&result).unwrap();

        // Invalid JSON should produce error envelope
        prop_assert!(
            envelope["ok"] == false,
            "Invalid JSON input must produce error envelope"
        );

        // Error should indicate invalid_json
        let code = envelope["error"]["code"].as_str().unwrap_or("");
        prop_assert!(
            code == "invalid_json" || code == "invalid_settings",
            "Invalid JSON should produce invalid_json or invalid_settings error, got: {}",
            code
        );
    }

    /// Test that unknown mode returns error with unknown_mode code.
    #[test]
    fn prop_unknown_mode_returns_unknown_mode_error(
        unknown_mode in unknown_mode_strategy()
    ) {
        let result = run_json(&unknown_mode, "{}");
        let envelope: Value = serde_json::from_str(&result).unwrap();

        // Should be error envelope
        prop_assert!(
            envelope["ok"] == false,
            "Unknown mode must produce error envelope"
        );

        // Should have unknown_mode error code
        let code = envelope["error"]["code"].as_str().unwrap_or("");
        prop_assert_eq!(
            code, "unknown_mode",
            "Unknown mode should produce 'unknown_mode' error code, got: {}",
            code
        );
    }
}

// Property 2: Monotonicity
//
// Invariant: Adding more invalid inputs should never reduce the error count
// or produce a success result where an error previously occurred.
proptest! {
    /// Test that invalid boolean field type produces error (not silent fallback).
    #[test]
    fn prop_strict_parsing_invalid_bool_type_produces_error(
        field in boolean_field_strategy(),
        invalid_value in invalid_value_strategy()
    ) {
        let args = format!(r#"{{"{}": "{}"}}"#, field, invalid_value);
        let result = run_json("lang", &args);
        let envelope: Value = serde_json::from_str(&result).unwrap();

        // Invalid type should produce error, not use default
        prop_assert!(
            envelope["ok"] == false,
            "Invalid type for '{}' should produce error, got success: {:?}",
            field, envelope
        );

        let code = envelope["error"]["code"].as_str().unwrap_or("");
        prop_assert_eq!(
            code, "invalid_settings",
            "Invalid type should produce 'invalid_settings' error"
        );
    }

    /// Test that invalid numeric field type produces error.
    #[test]
    fn prop_strict_parsing_invalid_numeric_type_produces_error(
        (mode, field) in numeric_field_strategy(),
        invalid_value in proptest::string::string_regex("[a-z]+").unwrap()
    ) {
        let args = format!(r#"{{"{}": "{}"}}"#, field, invalid_value);
        let result = run_json(&mode, &args);
        let envelope: Value = serde_json::from_str(&result).unwrap();

        // Invalid type should produce error
        prop_assert!(
            envelope["ok"] == false,
            "Invalid numeric type for '{}.{}' should produce error",
            mode, field
        );

        let code = envelope["error"]["code"].as_str().unwrap_or("");
        prop_assert_eq!(
            code, "invalid_settings",
            "Invalid numeric type should produce 'invalid_settings' error"
        );
    }
}

/// Test that empty string mode produces error.
#[test]
fn test_empty_mode_returns_error() {
    let result = run_json("", "{}");
    let envelope: Value = serde_json::from_str(&result).unwrap();

    assert!(envelope["ok"] == false, "Empty mode should produce error");
}

// Property 3: No Panic (Totality)
//
// Invariant: The run_json function must be total - it must return
// valid JSON for ALL possible string inputs without panicking.
proptest! {
    /// Test that ANY string input to run_json produces valid JSON output.
    /// This is the critical totality property.
    #[test]
    fn prop_run_json_is_total_function(
        mode_bytes in proptest::collection::vec(any::<u8>(), 0..100),
        args_bytes in proptest::collection::vec(any::<u8>(), 0..200)
    ) {
        // Convert arbitrary bytes to string (may contain invalid UTF-8)
        let mode = String::from_utf8_lossy(&mode_bytes);
        let args = String::from_utf8_lossy(&args_bytes);

        // CRITICAL INVARIANT: This must never panic
        let result = std::panic::catch_unwind(|| {
            run_json(&mode, &args)
        });

        prop_assert!(
            result.is_ok(),
            "run_json must never panic, even on arbitrary byte input"
        );

        // The result must be valid JSON
        let json_output = result.unwrap();
        let parsed: Result<Value, _> = serde_json::from_str(&json_output);

        prop_assert!(
            parsed.is_ok(),
            "run_json must always return valid JSON, got: {}",
            json_output
        );

        // Must have required envelope structure
        let envelope = parsed.unwrap();
        prop_assert!(
            envelope.get("ok").is_some(),
            "Envelope must have 'ok' field"
        );
    }

    /// Test that deeply nested JSON doesn't cause stack overflow or panic.
    #[test]
    fn prop_deeply_nested_json_handled_gracefully(
        depth in 10usize..100
    ) {
        // Create deeply nested JSON: {"a":{"a":{"a":...}}}
        let mut nested = "0".to_string();
        for _ in 0..depth {
            nested = format!(r#"{{"a":{}}}"#, nested);
        }

        // Wrap in valid args structure
        let args = format!(r#"{{"scan": {}}}"#, nested);

        // Must not panic
        let result = std::panic::catch_unwind(|| {
            run_json("version", &args)
        });

        prop_assert!(
            result.is_ok(),
            "Deeply nested JSON should not cause panic"
        );

        // Result must be valid JSON
        let json_output = result.unwrap();
        let parsed: Result<Value, _> = serde_json::from_str(&json_output);
        prop_assert!(
            parsed.is_ok(),
            "Must return valid JSON even for deeply nested input"
        );
    }

    /// Test that very long strings don't cause panic or OOM.
    #[test]
    fn prop_long_strings_handled_gracefully(
        len in 1000usize..10000
    ) {
        let long_string = "x".repeat(len);
        let args = format!(r#"{{"paths": ["{}"]}}"#, long_string);

        // Must not panic
        let result = std::panic::catch_unwind(|| {
            run_json("lang", &args)
        });

        prop_assert!(
            result.is_ok(),
            "Very long strings should not cause panic"
        );
    }
}

/// Regression tests for specific discovered edge cases.
#[cfg(test)]
mod regression_tests {
    use super::*;

    /// Ensure that null bytes in strings are handled.
    #[test]
    fn null_byte_in_mode_string() {
        let result = run_json("lang\0mode", "{}");
        let envelope: Value = serde_json::from_str(&result).unwrap();
        assert!(envelope.get("ok").is_some());
    }

    /// Ensure that Unicode replacement characters are handled.
    #[test]
    fn unicode_replacement_characters() {
        let result = run_json("\u{FFFD}\u{FFFE}", "{}");
        let envelope: Value = serde_json::from_str(&result).unwrap();
        assert!(envelope.get("ok").is_some());
    }

    /// Ensure that control characters don't break JSON output.
    #[test]
    fn control_characters_in_error_messages() {
        // This tests that error messages with special chars are properly escaped
        let result = run_json("<script>alert(1)</script>", "{}");
        let envelope: Value = serde_json::from_str(&result).unwrap();
        assert!(envelope.get("ok").is_some());

        // Re-serialize to ensure it's valid JSON
        let re_encoded = serde_json::to_string(&envelope).unwrap();
        assert!(!re_encoded.is_empty());
    }
}
