//! render_md.rs — Markdown rendering tests using static fixture
//!
//! This test uses a static JSON fixture (`sample-receipt.json`) instead of
//! calling the full `analyze()` pipeline. The fixture was generated by
//! running `analyze()` once with the following inputs:
//! - ExportData with 3 FileRow entries (src/lib.rs, tests/lib_test.rs, Cargo.toml)
//! - AnalysisPreset::Receipt
//! - ANALYSIS_SCHEMA_VERSION = 9
//!
//! To regenerate the fixture:
//! 1. Temporarily re-add tokmd-analysis dev-dependency to Cargo.toml
//! 2. Add fixture generation code to the test (see git history)
//! 3. Run: cargo test -p tokmd-format analysis --test render_md
//! 4. Verify the generated JSON and copy to test-fixtures/sample-receipt.json
//! 5. Remove dev-dependency and generation code
//!
//! The integrity hash in the fixture must remain stable:
//! cbb1dbe65f3ace4a53b2597a8c7512ba6eb2cd6d5bd5ef13b05cc0830deeae5d

use tokmd_analysis_types::AnalysisReceipt;
use tokmd_format::analysis::render;
use tokmd_types::AnalysisFormat;

static SAMPLE_RECEIPT_JSON: &str = include_str!("../test-fixtures/sample-receipt.json");

#[test]
fn render_md_snapshot() {
    let receipt: AnalysisReceipt = serde_json::from_str(SAMPLE_RECEIPT_JSON)
        .expect("fixture should deserialize to AnalysisReceipt");

    let rendered = render(&receipt, AnalysisFormat::Md).expect("render");
    let text = match rendered {
        tokmd_format::analysis::RenderedOutput::Text(s) => s,
        tokmd_format::analysis::RenderedOutput::Binary(_) => panic!("expected text"),
    };

    // Content-feature enrichers (duplicates, complexity, API surface) produce
    // additional zero-value sections when tokmd-analysis is compiled with the
    // `content` feature.  CI runs `cargo test --all-features` (workspace-wide)
    // which activates these enrichers, whereas local per-package testing does
    // not.  Use a separate snapshot for each variant so both passes succeed.
    if text.contains("## Duplicates") {
        insta::assert_snapshot!("render_md_snapshot_content", text);
    } else {
        insta::assert_snapshot!("render_md_snapshot", text);
    }
}
