//! Cockpit task for CI orchestration.
//!
//! This task wraps `tokmd cockpit` and adds CI-specific features like
//! posting comments to GitHub PRs.

use std::process::Command;

use anyhow::{Context, Result, bail};

use crate::cli::CockpitArgs;

pub fn run(args: CockpitArgs) -> Result<()> {
    // Run tokmd cockpit to generate metrics
    let format_arg = match args.format.as_str() {
        "md" => "md",
        "sections" => "sections",
        _ => "json",
    };

    let output = Command::new("cargo")
        .arg("run")
        .arg("-p")
        .arg("tokmd")
        .arg("--release")
        .arg("--")
        .arg("cockpit")
        .arg("--base")
        .arg(&args.base)
        .arg("--head")
        .arg(&args.head)
        .arg("--format")
        .arg(format_arg)
        .output()
        .context("Failed to run tokmd cockpit")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("tokmd cockpit failed: {}", stderr.trim());
    }

    let cockpit_output = String::from_utf8_lossy(&output.stdout);

    // If posting comment, use gh CLI
    if args.post_comment {
        let pr_number = args
            .pr_number
            .ok_or_else(|| anyhow::anyhow!("--pr-number is required when using --post-comment"))?;

        post_pr_comment(pr_number, &cockpit_output)?;
        println!("Posted cockpit metrics to PR #{}", pr_number);
    } else {
        // Just print the output
        print!("{}", cockpit_output);
    }

    Ok(())
}

fn post_pr_comment(pr_number: u64, body: &str) -> Result<()> {
    // Check if gh CLI is available
    let gh_check = Command::new("gh")
        .arg("--version")
        .output()
        .context("gh CLI is not available")?;

    if !gh_check.status.success() {
        bail!("gh CLI is not available or not authenticated");
    }

    // Format comment body with cockpit header
    let comment_body = format!(
        "## Glass Cockpit\n\n\
         <details>\n\
         <summary>PR Metrics</summary>\n\n\
         {}\n\n\
         </details>\n\n\
         ---\n\
         *Generated by `tokmd cockpit`*",
        body
    );

    // Post comment using gh CLI
    let status = Command::new("gh")
        .arg("pr")
        .arg("comment")
        .arg(pr_number.to_string())
        .arg("--body")
        .arg(&comment_body)
        .status()
        .context("Failed to run gh pr comment")?;

    if !status.success() {
        bail!("gh pr comment failed");
    }

    Ok(())
}
