/* auto-generated by NAPI-RS */

export interface LangOptions {
  paths?: string[]
  top?: number
  files?: boolean
  children?: 'collapse' | 'separate'
  redact?: 'none' | 'paths' | 'all'
  excluded?: string[]
  hidden?: boolean
}

export interface ModuleOptions {
  paths?: string[]
  top?: number
  module_roots?: string[]
  module_depth?: number
  children?: 'separate' | 'parents-only'
  redact?: 'none' | 'paths' | 'all'
  excluded?: string[]
  hidden?: boolean
}

export interface ExportOptions {
  paths?: string[]
  format?: 'jsonl' | 'json' | 'csv' | 'cyclonedx'
  min_code?: number
  max_rows?: number
  meta?: boolean
  strip_prefix?: string
  module_roots?: string[]
  module_depth?: number
  children?: 'separate' | 'parents-only'
  redact?: 'none' | 'paths' | 'all'
  excluded?: string[]
  hidden?: boolean
}

export interface AnalyzeOptions {
  paths?: string[]
  preset?: 'receipt' | 'estimate' | 'health' | 'risk' | 'supply' | 'architecture' | 'topics' | 'security' | 'identity' | 'git' | 'deep' | 'fun'
  window?: number
  git?: boolean
  max_files?: number
  max_bytes?: number
  max_commits?: number
  excluded?: string[]
  hidden?: boolean
}

export interface LangRow {
  lang: string
  code: number
  lines: number
  files: number
  bytes: number
  tokens: number
  avg_lines: number
}

export interface ModuleRow {
  module: string
  code: number
  lines: number
  files: number
  bytes: number
  tokens: number
  avg_lines: number
}

export interface FileRow {
  path: string
  module: string
  lang: string
  kind: 'parent' | 'child'
  code: number
  comments: number
  blanks: number
  lines: number
  bytes: number
  tokens: number
}

export interface Totals {
  code: number
  lines: number
  files: number
  bytes: number
  tokens: number
  avg_lines: number
}

export interface LangReceipt {
  schema_version: number
  generated_at_ms: number
  tool: { name: string; version: string }
  mode: 'lang'
  status: 'complete' | 'partial'
  warnings: string[]
  scan: object
  args: object
  rows: LangRow[]
  total: Totals
  with_files: boolean
  children: string
  top: number
}

export interface ModuleReceipt {
  schema_version: number
  generated_at_ms: number
  tool: { name: string; version: string }
  mode: 'module'
  status: 'complete' | 'partial'
  warnings: string[]
  scan: object
  args: object
  rows: ModuleRow[]
  total: Totals
  module_roots: string[]
  module_depth: number
  children: string
  top: number
}

export interface ExportReceipt {
  schema_version: number
  generated_at_ms: number
  tool: { name: string; version: string }
  mode: 'export'
  status: 'complete' | 'partial'
  warnings: string[]
  scan: object
  args: object
  rows: FileRow[]
  module_roots: string[]
  module_depth: number
  children: string
}

export interface DiffTotals {
  old_code: number
  new_code: number
  delta_code: number
  old_lines: number
  new_lines: number
  delta_lines: number
  old_files: number
  new_files: number
  delta_files: number
  old_bytes: number
  new_bytes: number
  delta_bytes: number
  old_tokens: number
  new_tokens: number
  delta_tokens: number
}

export interface DiffReceipt {
  schema_version: number
  generated_at_ms: number
  tool: { name: string; version: string }
  mode: 'diff'
  from_source: string
  to_source: string
  diff_rows: object[]
  totals: DiffTotals
}

/**
 * Get the tokmd version string.
 * @returns The version of tokmd (e.g., "1.3.1")
 */
export function version(): string

/**
 * Get the JSON schema version.
 * @returns The current schema version for receipts
 */
export function schemaVersion(): number

/**
 * Run a tokmd operation with JSON arguments, returning a JSON string.
 * @param mode - The operation mode
 * @param argsJson - JSON string containing the arguments
 * @returns Promise resolving to JSON string
 */
export function runJson(mode: string, argsJson: string): Promise<string>

/**
 * Run a tokmd operation and return the result as an object.
 * @param mode - The operation mode
 * @param args - Object containing the arguments
 * @returns Promise resolving to the result object
 */
export function run(mode: string, args: object): Promise<object>

/**
 * Scan paths and return a language summary.
 * @param options - Scan options
 * @returns Promise resolving to language receipt
 */
export function lang(options?: LangOptions): Promise<LangReceipt>

/**
 * Scan paths and return a module summary.
 * @param options - Scan options
 * @returns Promise resolving to module receipt
 */
declare function module(options?: ModuleOptions): Promise<ModuleReceipt>
export { module }

/**
 * Scan paths and return file-level export data.
 * @param options - Export options
 * @returns Promise resolving to export receipt
 */
declare function exportFn(options?: ExportOptions): Promise<ExportReceipt>
export { exportFn as export }

/**
 * Run analysis on paths and return derived metrics.
 * @param options - Analysis options
 * @returns Promise resolving to analysis receipt
 */
export function analyze(options?: AnalyzeOptions): Promise<object>

export interface DiffOptions {
  from: string
  to: string
}

/**
 * Compare two receipts or paths and return a diff.
 * Backward-compatible call form:
 * `diff(fromPath, toPath)`.
 * @returns Promise resolving to diff receipt
 */
export function diff(fromPath: string, toPath: string): Promise<DiffReceipt>
/**
 * Preferred call form using an options object.
 * @param options - Diff options
 * @returns Promise resolving to diff receipt
 */
export function diff(options?: DiffOptions | null): Promise<DiffReceipt>
